version: 0.2.15.{build}

#environment:

platform: 
  - x64

configuration: Release

clone_folder: c:\projects\OpenBLAS

init:
  - git config --global core.autocrlf input

build:
  project: OpenBLAS.sln

clone_depth: 5

#branches to build
branches:
  only:
    - master
    - develop
    - cmake

skip_tags: true

matrix:
  fast_finish: true

skip_commits:
# Add [av skip] to commit messages
  message: /\[av skip\]/

before_build:
  - echo Running cmake...
  - cd c:\projects\OpenBLAS
  - cmake -G "Visual Studio 12 Win64" .

test_script:
  - echo Build OK!
