site_name: DataVec documentation
theme: readthedocs
docs_dir: doc_sources
repo_url: https://github.com/deeplearning4j/deeplearning4j
site_url: http://deeplearning4j.org
site_description: 'DataVec documentation'

dev_addr: '0.0.0.0:8000'

pages:
- Home: index.md
- Overview of supported features: supported-features.md
- Getting started:
  - Guide to KerasSequentialModel: getting-started/keras-sequential-guide.md
  - Guide to KerasModel: getting-started/keras-model-guide.md
- Models:
  - KerasSequentialModel: models/sequential.md
  - KerasModel (functional API): models/model.md
- Layers:
  - About Keras import layers: layers/about-importing-layers.md
  - Core Layers: layers/core.md
  - Convolutional Layers: layers/convolutional.md
  - Pooling Layers: layers/pooling.md
  - Recurrent Layers: layers/recurrent.md
  - Embedding Layers: layers/embeddings.md
  - Advanced Activations Layers: layers/advanced-activations.md
  - Normalization Layers: layers/normalization.md
  - Noise layers: layers/noise.md
  - Layer wrappers: layers/wrappers.md
  - Writing custom import layers: layers/writing-custom-import-layers.md
- Losses: losses.md
- Optimizers: optimizers.md
- Activations: activations.md
- Backend: backend.md
- Initializers: initializers.md
- Regularizers: regularizers.md
- Constraints: constraints.md
